# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_auto_20170923_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleset',
            name='attacker_size',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='battle_number',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='defender_size',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='major_capture',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='major_death',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='summer',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='year',
            field=models.IntegerField(default='', null=True),
        ),
    ]
