# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_auto_20170923_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleset',
            name='attacker_king',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='attacker_outcome',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='battle_type',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='defender_king',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='location',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='name',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='battleset',
            name='region',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
